#
# Module manifest for module 'RESAM'
#
# Generated by: Luc Dekens
#
# Generated on: June 1st 2014
#

@{

# Script module or binary module file associated with this manifest
ModuleToProcess = 'RESAM.psm1'

# Version number of this module.
ModuleVersion = '1.0'

# ID used to uniquely identify this module
GUID = 'e3ee3df5-5819-455b-aaf1-2f63858f7874'

# Author of this module
Author = 'Luc Dekens'

# Company or vendor of this module
CompanyName = 'http://lucd.info'

# Copyright statement for this module
Copyright = 'Copyright © 2014 Luc Dekens All rights reserved. '

# Description of the functionality provided by this module
Description = 'RES Automation Manager functions'

# Minimum version of the Windows PowerShell engine required by this module
PowerShellVersion = '3.0'

# Name of the Windows PowerShell host required by this module
PowerShellHostName = ''

# Minimum version of the Windows PowerShell host required by this module
PowerShellHostVersion = ''

# Minimum version of the .NET Framework required by this module
DotNetFrameworkVersion = ''

# Minimum version of the common language runtime (CLR) required by this module
CLRVersion = ''

# Processor architecture (None, X86, Amd64, IA64) required by this module
ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
RequiredModules = @()

# Assemblies that must be loaded prior to importing this module
RequiredAssemblies = @()

# Script files (.ps1) that are run in the caller's environment prior to importing this module
ScriptsToProcess = @("RESAM-Init.ps1")

# Type files (.ps1xml) to be loaded when importing this module
TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
FormatsToProcess = @()

# Modules to import as nested modules of the module specified in ModuleToProcess
NestedModules = @()

# Functions to export from this module
FunctionsToExport = 'Test-ResAM','Get-ResAMModule','Get-ResAMProject','Get-ResAMRunBook','Get-ResAMInputParameter','Get-ResAMJob',
  'Get-ResAMJobByID','Get-ResAMJobResult','Get-ResAMRunBookJob','New-ResAMJob','Stop-ResAMJob','Get-ResAMAgent','Get-ResAMJobUsage',
  'Get-ResAMTeams'

# Cmdlets to export from this module
CmdletsToExport = '*'

# Variables to export from this module
VariablesToExport = '*'

# Aliases to export from this module
AliasesToExport = '*'

# List of all modules packaged with this module
ModuleList = @()

# List of all files packaged with this module
FileList = @("RESAM.psm1","RESAM.psd1","RESAM-Init.ps1","RESAM.psm1-help.xml")

# Private data to pass to the module specified in ModuleToProcess
PrivateData = @{
    "PageSize"=500
    "DaysBackDefault" = 1
}

}

